openapi: 3.0.3
info:
    title: Calculator Service
    description: Service for multiplying numbers, a Goa teaser
    version: 0.0.1
servers:
    - url: http://localhost:8000
paths:
    /:
        post:
            tags:
                - calc
            summary: divide calc
            operationId: calc#divide
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DivideRequestBody'
                        example:
                            dividend: 1223785466250741194
                            divisor: 1260092214909975097
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivideResponseBody'
                            example:
                                quotient: 726699518895697570
                                reminder: 2832069076395640246
                "400":
                    description: 'div_by_zero: Response used for division by zero errors'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivByZero'
                            example:
                                message: Minus consectetur mollitia ea architecto error.
                "504":
                    description: 'timeout: Operation timed out'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        DivByZero:
            type: object
            properties:
                message:
                    type: string
                    description: division by zero leads to infinity.
                    example: Ratione consequatur omnis et reiciendis numquam dicta.
            description: division by 0
            example:
                message: Aliquid architecto dignissimos neque ullam.
            required:
                - message
        DivideRequestBody:
            type: object
            properties:
                dividend:
                    type: integer
                    example: 2621667945400044094
                    format: int64
                divisor:
                    type: integer
                    example: 3479209296192704251
                    format: int64
            example:
                dividend: 6654640499905032994
                divisor: 5922996389565946978
            required:
                - dividend
                - divisor
        DivideResponseBody:
            type: object
            properties:
                quotient:
                    type: integer
                    example: 5462138215859642042
                    format: int64
                reminder:
                    type: integer
                    example: 7122976781143536797
                    format: int64
            example:
                quotient: 633948248488593041
                reminder: 3012441810639728333
            required:
                - quotient
                - reminder
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
tags:
    - name: calc
